spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/booksdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway:
    enabled: true
server:
  port: 8081
logging:
  level:
    # входной REST-контроллер
    com.bookfinder.search.controller: DEBUG
    # основной сервис поиска
    com.bookfinder.search.service.SearchService: DEBUG
    # HTTP-клиент (WebClient)
    org.springframework.web.reactive.function.client: TRACE
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    com.bookfinder.search.provider.LitresProvider: DEBUG
    # Feign-клиент в catalog-service
    feign: DEBUG

  #  если нужен файл-лог – оставьте этот блок,
  #  иначе закомментируйте
  file:
    name: logs/search-service.log
